osx_image: xcode8
sudo: false
notifications:
  email: false
language: objective-c
rvm:
  - 2.3.1
service_name: travis-pro
repo_token: 9u4s2QLGYCvlB15SAqThI9eSY732ypUFz
before_install: 
  gem install bundler;
  bundle install;
script:
  bundle exec rake;
  bundle exec exe/pandora create Cua org.test;
  cd Cua;
  make build;
  make spec;

